### ISSUE TITLE
Some country/region name changed

### ISSUE THREAD

**Issue by gitissueask** [DrFabach/Corona#2]
Due to some change in the data, the case numbers in some countries were not shown correctly when the mouse was moved there. 

Please consider adding the following lines after line 45 :

```
data$`Country/Region`[data$`Country/Region`=="Korea, South"]<- "South Korea"
data$`Country/Region`[data$`Country/Region`=="Taiwan*"]<- "Taiwan"
data$`Country/Region`[data$`Country/Region`=="Holy See"]<- "Vatican"
```

**Comment by DrFabach** [comment]
Thanks for the notification, I modified the script
