### ISSUE TITLE
Plot cases over time

### ISSUE THREAD

**Issue by Johne3112** [DrFabach/Corona#3]
Hi I was just playing with your code to see if I could plot cases ove time.  I'm sure you've already looked at this but I think it would be a useful additional tab on you app.  Here is a sample code to summarise and plot by country over time.  The first plot is a normal y axis, the second plot is an log y axis.

URL <- RCurl::getURL("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
data <- read.csv(text = URL, check.names = F)

df <-data %>% tidyr::pivot_longer(-c(`Province/State`,`Country/Region`,Lat,Long), names_to = "date", values_to = "cases")
df <- df[,c(1,2,5,6)]

df$date <- lubridate::parse_date_time(df$date, orders = c("mdy"))

df <- df %>% dplyr::group_by(`Country/Region`,date) %>% dplyr::summarise(cases = sum(cases))

plotly::plot_ly(df,x = ~date, y = ~cases, color = ~`Country/Region`, type = "scatter",mode = "lines")
  

plotly::plot_ly(df,x = ~date, y = ~cases, color = ~`Country/Region`, type = "scatter",mode = "lines") %>%
  layout(yaxis = list(type = "log"))

**Comment by DrFabach** [comment]
Hi,
Thank you for your suggestion.

I will see tomorrow how i can add it to the map.

**Comment by DrFabach** [comment]
I add a new branch, Tell me if it was something like that you had in mind.

**Comment by Johne3112** [comment]
I've just downloaded and tried to run locally on my PC but its missing shapefile.rdata 
Is this a generic file I can get from somewhere?

**Comment by DrFabach** [comment]
The files is in the master branch

**Comment by Johne3112** [comment]
Thanks that looks really good.  Yes exactly what I had in mind
